### ISSUE TITLE
quill Overwriting modules/ImageUploader with class...

### ISSUE THREAD

**Issue by hsiangfeng** [vueup/vueup-quill#384]
**Version**
@vueup/vue-quill version 1.1.0

**Describe the bug**

**To Reproduce**
1. register modules/ImageUploader
2. Click Button v-if toggle QuillEditor
3. See Error 「quill Overwriting modules/ImageUploader with class ...」

**Expected behavior**

![圖片](https://github.com/vueup/vue-quill/assets/19990752/7e99cdd3-de19-4b89-bbde-120af58bf17c)

now show error.

**Reproduction link**
Link：https://codesandbox.io/s/blissful-haze-7vlsm5

**Browser (please complete the following information):**
 - Browser：Firefox
 - Version：114.0.1

**Additional context**
no.

**Comment by hank2718** [comment]
I also have the same problem！

**Comment by hsiangfeng** [comment]
> I also have the same problem！

Hey! I found a solution later! The solution is just to use the following method

```js
if (!Quill. imports['modules/ImageUploader']) {
   Quill. register('modules/ImageUploader', ImageUploader);
}
```

I also wrote an article, you can refer to it~
[https://israynotarray.com/javascript/20230629/1402048802/](https://israynotarray.com/javascript/20230629/1402048802/)

Since this problem is solved, I'm closing this issue.
