### ISSUE TITLE
Globally registered Modules have their options overwritten

### ISSUE THREAD

**Issue by da5idb** [vueup/vueup-quill#392]
**Version**
@vueup/vue-quill version 1.2.0

**Describe the bug**
I want to globally register an module like: `Quill.register('modules/mention', Mention) `
I have to provide options for the module to the quill editor - and would do it in the modules section of the options: options.modules - It seems like this was the intention from the code in QuillEditor.ts:151
Sadly it seems like this does not work as intended as the options are overwritten. 

This only works if I do not have any modules defined - for me for example the toolbar is always there and means that the module options are not merged correctly
But also defining other modules on the props.modules would mean that module options are overwritten since they are not included in 
`clientOptions.modules = Object.assign({}, clientOptions.modules, modules)`

So in essence we always overwrite the modules section from the options.

**To Reproduce**
1. Globally register a module
2. Provide options through the modules section of the options object
3. Enable external toolbar with :toolbar="#someId"
4. See that the options were overwritten by stepping through the code or checking the Quill instance options

**Expected behavior**
The modules section of the options should not be overwritten 

**Additional context**
The issue would not be a big one if the PR https://github.com/vueup/vue-quill/pull/360 would be included in the 1.2.0 release. Since that is missing we reregister the modules for every editor on screen and get the warning about that.
Is it maybe possible to release a minor version with that fix? Also a small section in the docs about how to register modules globally would be nice if that is something we should be able to do :)

**Comment by da5idb** [comment]
If it helps I could open a PR that fixes this issue - my proposed fix would be: 
```
if (props.options?.modules) {
    clientOptions.modules = Object.assign({}, clientOptions.modules, props.options.modules)
}
```
After the  if (props.modules) { ... }  part of the composeOptions function.

The order is chosen since I think locally provided options should override the module options.

**Comment by mkgn** [comment]
@da5idb - Were you able to get [Quill-mention](https://github.com/quill-mention/quill-mention/tree/master) to work with Vu3 quill plugin?

**Comment by da5idb** [comment]
@mkgn yes that was never really the issue - registering the module in the options works. It is showing the hint that the module is registered already and overwritten. But since I use it with the same options everywhere that is not really a big issue - apart from the console spam.
I still think registering globally would be the best so maybe I will do my PR and try to get that merged.

**Comment by da5idb** [comment]
Added a PR - not sure I did this correctly with the fork of the Repo - if this is the wrong way to do it I am sorry about that
