### ISSUE TITLE
Moderate severity vulnerability

### ISSUE THREAD

**Issue by Jacobtims** [vueup/vueup-quill#404]
**Version**
@vueup/vue-quill version 1.2.0

**Describe the bug**
@vueup/vue-quill 1.2.0 depends on version **<=1.3.7** of **quill**, which contains a **security vulnerability**.
```
Severity: moderate
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
No fix available
node_modules/quill
  @vueup/vue-quill  *
  Depends on vulnerable versions of quill
  node_modules/@vueup/vue-quill
```

More info about the vulnerability here: https://github.com/advisories/GHSA-4943-9vgg-gr5r

**Comment by OleksiiMalitskyi** [comment]
I'm still having a problem with focus loss. 
Overflow propertis not behaving correctly.
