### ISSUE TITLE
`enable` props not work when initial 

### ISSUE THREAD

**Issue by Spike-Leung** [vueup/vueup-quill#407]
**Version**
@vueup/vue-quill version [1.2.0]

**Describe the bug**
With `enable="false"`, vue-quill can still edit when init. 
![image](https://github.com/vueup/vue-quill/assets/30440218/7f34e96b-6e75-40c8-8fd9-d1145927c54c)
![image](https://github.com/vueup/vue-quill/assets/30440218/dfa55815-0ea2-4758-bd7c-9c711f31986a)

**To Reproduce**
1. Set `enable=false`
2. Refresh page
3. Text in vue-quill component

**Expected behavior**
According to [enable](https://vueup.github.io/vue-quill/api/#enable), when `enable=false`, it should prevent text

**Reproduction link**
If available, add a link to the source code to help explain your problem.

**Browser (please complete the following information):**
 - Browser [chrome]
 - Version [115]

**Comment by Spike-Leung** [comment]
Context:
I have a toggle button to toggle vue-quill enable.
By default, it can not edit, when I click the `edit` button, it can edit, after the edit, I may click the `save` button and disable vue-quill edit.

**Comment by xdmrpgy** [comment]
I have the same problem!

**Comment by Spike-Leung** [comment]
> I have the same problem!

Here is a workaround: 
Listen vue-quill's `ready` event, after inited, trigger quill `enable` API
```javascript
    <QuillEditor
      theme="snow"
      :toolbar="toolbar"
      :enable="isEdit"
      ref="quillRef"
      @ready="init()"
    />
```
```javascript
  const quillRef = ref(null)
  const isEdit = ref(false)
  const init = () => {
      quillRef.value.getQuill().enable(isEdit.value)
   }
```

**Comment by xdmrpgy** [comment]
> > I have the same problem!
> 
> Here is a workaround: Listen vue-quill's `ready` event, after inited, trigger quill `enable` API
> 
> ```js
>     <QuillEditor
>       theme="snow"
>       :toolbar="toolbar"
>       :enable="isEdit"
>       ref="quillRef"
>       @ready="init()"
>     />
> ```
> 
> ```js
>   const quillRef = ref(null)
>   const isEdit = ref(false)
>   const init = () => {
>       quillRef.value.getQuill().enable(isEdit.value)
>    }
> ```

thanks bro! It works, but I found a new problem. When placeholder has content and the quill editor is readonly, it still shows the placeholder.
![Snipaste_2023-08-22_11-16-05](https://github.com/vueup/vue-quill/assets/11405666/cd4b570c-3e86-4468-b520-b692221c354c)

**Comment by Spike-Leung** [comment]
> 

hmm... maybe you can make `placeholder` as a computed properties which computed by readonly
