### ISSUE TITLE
Is it possible to customize icons?

### ISSUE THREAD

**Issue by sandranrivas** [vueup/vueup-quill#417]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.5]

**Describe the bug**
I would like to use the font awesome icons, as default, but I dont find anything on the guideline

**Comment by gokhantaskan** [comment]
Have you tried this?
https://vueup.github.io/vue-quill/guide/toolbar.html#custom-toolbar-container

I haven't tested it but just saw it in the documentation.
