### ISSUE TITLE
How to add custom css class 

### ISSUE THREAD

**Issue by rahul37865** [vueup/vueup-quill#429]
I am using Nuxt 3 and Tailwind CSS. I have implemented vue-quill. I want to add custom css class in editor's elements e.g. blockquote, ul, li etc. 

Reason:-
Tailwind CSS removes number and bullet from `<ul>` and `<ol> `tags so when i display Editor contents on web page All `<ul> `and `<ol>` are without number and bullet. I need to inject tailwind css class to make them work properly. 

So far i have code as below
```
<script setup>
import { QuillEditor } from '@vueup/vue-quill';
import '@vueup/vue-quill/dist/vue-quill.snow.css';
const formData = ref({
  content: undefined,
})
const submitProductForm = async () => {
  const fData = new FormData();
  fData.append('content', JSON.stringify(formData.value.content)); 
  await useFetch('product/', { method: 'POST', body: fData })
};
</script>
<template>
<div>
 <form ref="form" @submit.prevent="submitProductForm">
  <ClientOnly>
   <p class="mt-5">Content</p>
   <QuillEditor theme="snow" toolbar="full" placeholder="write content..." v-model:content="formData.content" />
  </ClientOnly>
  <button type="submit">Submit</button>
</div>
</template>
```

**Comment by TerrniT** [comment]
@rahul37865 Hi! You can use `style` tag with scss to customize individual elements by using `@apply` with tailwind classes. Example: 
![Снимок экрана от 2023-11-13 13-31-36](https://github.com/vueup/vue-quill/assets/104818206/f4743847-b62b-49b2-9336-6d531db3a032)
![Снимок экрана от 2023-11-13 13-32-05](https://github.com/vueup/vue-quill/assets/104818206/098dcfc3-9d7c-4a84-ac93-b959f079299d)
![Снимок экрана от 2023-11-13 13-32-21](https://github.com/vueup/vue-quill/assets/104818206/a7a09447-e01c-4864-b059-7a8f32fbf71c)
