### ISSUE TITLE
Issue: Need a simple way to erase all the content.

### ISSUE THREAD

**Issue by AndreiBil** [vueup/vueup-quill#434]
The content inside the editor is not cleared out.

Steps to reproduce:
1. Visit https://vueup.github.io/vue-quill/ 
2. Type something in the Quill Editor
3. Erase everything you typed  ( CMD + A & Backspace)
4. Use inspect element and notice there is a "br" wrapped around by a "p" or "h1" tag.

The issue is that the data in my column now looks like this and its not empty
<img width="309" alt="image" src="https://github.com/vueup/vue-quill/assets/26352183/77705549-19ec-43a7-bad4-4ea9b7f057f0">
:

Thanks

**Comment by claide** [comment]
I encountered this as well today. I wrap the quill editor to a custom component and call it on a page. After a post request, I want to clear the data inside the editor.

**Comment by leejhlouis** [comment]
I also encountered this issue

**Comment by claide** [comment]
Okay here's what I did on vue 3 to clear the content

```
watch(() => props.modelValue, (newVal) => {
  if (editor.value) {
    if (newVal !== editor.value.getHTML()) {
      editor.value.setHTML(newVal)
    }
  }
})
```
