### ISSUE TITLE
their is no exclude button in quill ? 

### ISSUE THREAD

**Issue by xalteropsx** [vueup/vueup-quill#441]
<QuillEditor toolbar="full" theme="snow" />  suppose i want to hide or remove video button how can i achieve that ?

**Comment by makerovski** [comment]
Hi!

I had a problem like this, I solved it just hiding it with css, and also for translations

<img width="570" alt="Bildschirmfoto 2023-11-16 um 10 50 32" src="https://github.com/vueup/vue-quill/assets/86009432/469bbc21-0a59-4700-9b1c-e363f826db75">
