### ISSUE TITLE
Nuxt 3 Vite Error

### ISSUE THREAD

**Issue by jamacon36** [vueup/vueup-quill#465]
**Version**
@vueup/vue-quill version 1.2.0

**Description**
In a Nuxt 3 implementation using Vite adding the `QuillEditor` component causes the following error when building:
```
The requested module '/_nuxt/@fs/../../../client-nuxt/node_modules/@vueup/vue-quill/node_modules/quill-delta/dist/Delta.js?v=a3a51558' does not provide an export named 'default'
```

It seems to be complaining not about vue-quill but a nested dependency.

**Config context**
nuxt.config.ts
```js
export default defineNuxtConfig({
  // ... other code
  vite: {
    optimizeDeps: {
      exclude: [
        '@vueup/vue-quill'
      ]
    }
  },
```
Wysiwyg.client.vue (SFC Component)
```vue
<script setup>
  import { QuillEditor } from '@vueup/vue-quill';
  import '@vueup/vue-quill/dist/vue-quill.snow.css';
</script>
<template>
    <QuillEditor
      theme="snow"
    />
</template>
```

**Comment by jamacon36** [comment]
## Update
Found a solution for others interested. In my nuxt.config.ts I replaced the `exclude` prop of the `optimizeDeps` config object with the `include` prop instead:
```js
  vite: {
    optimizeDeps: {
      include: [
        '@vueup/vue-quill'
      ]
    }
  },
```

**Comment by tbenoist1** [comment]
you just save me a lot of time thanks !
