### ISSUE TITLE
Bold isn't work 

### ISSUE THREAD

**Issue by monkuver** [vueup/vueup-quill#474]
**Version**
@vueup/vue-quill version [e.g. 1.2.0]

**Describe the bug**
When I try to use the button to make the text bold nothing happens

**To Reproduce**
Steps to reproduce the behaviour:
1. Inject quill CSS and the component itself into a single file component
2. Run application
3. Open the browser with a page which has the component
4. Apply the bold style by clicking the bold button on the toolbar and type any text or type any text, select part of it or the whole typed text and apply bold style by clicking the bold button

**Expected behaviour**
Text should become bold but nothing happens

**Browser (please complete the following information):**
 - Browser any
 - Vue 3.3.4

**Additional context**
<script setup lang="ts">
import '@vueup/vue-quill/dist/vue-quill.snow.css'
import { QuillEditor } from '@vueup/vue-quill'
</script>

<template>
  <main>
    <QuillEditor theme="snow" />
  </main>
</template>

**Comment by Choalstn** [comment]
same issue,, nothing update ??
