### ISSUE TITLE
V-model not work when content is setted to empty

### ISSUE THREAD

**Issue by overbost** [vueup/vueup-quill#484]
**Version**
@vueup/vue-quill 1.2.0

**Describe the bug**
When content is empty string, the quill content is not updated. The content is on the previous state
I must use
` this.$refs.quillEdtor.setHTML("")`

**To Reproduce**

```
<QuillEditor
 data-cy="textarea-full-desc"
 ref="quillEditor
 v-model:content="translation.full_desc"
 :placeholder="t('NO_FULL_DESC')"
 contentType="html"
 >

```

```
DevTools
content:""
contentType:"html"
enable:true
globalOptions:Object
modules:Object
theme:"snow"
modules:undefined
options:undefined
placeholder:"Aggiungi una descrizione dettagliata"
readOnly:false
theme:"snow"
toolbar:undefined
```

**Expected behavior**
The content should setted to empty

**Additional context**
I think there is a bug on the code

**Comment by wukaipeng-dev** [comment]
@axolo Worth to fix:
```
 watch(
      () => props.content,
      (newContent) => {
        if (!quill || !newContent || internalModelEquals(newContent)) return 👈👈👈👈👈

        // Restore the selection and cursor position after updating the content
        const selection = quill.getSelection()
        if (selection) {
          nextTick(() => quill?.setSelection(selection))
        }
        setContents(newContent)
      },
      { deep: true }
    )
```

**Comment by Xeyos88** [comment]
This problem makes it impossible to use it within a form.
It is not possible to check whether the content is empty

**Comment by maksimzinchuk** [comment]
try this to check if content is empty 
`function isEmpty(value: string) {
  return value.replace(/<(.|\n)*?>/g, "").trim().length === 0;
}`
