### ISSUE TITLE
SSR with @vueup/vue-quill

### ISSUE THREAD

**Issue by NicTorgersen** [vueup/vueup-quill#487]
**Version**
@vueup/vue-quill version 1.2.0

**Describe the bug**
Using this package with SSR gives an error:
```
/var/www/html/node_modules/quill/dist/quill.js:7661
    var elem = document.createElement('div');
           ^
ReferenceError: document is not defined
```

**To Reproduce**
1. Install `Laravel` with `Inertia` and `vite`
2. Set up `SSR` from `Inertia` docs: https://inertiajs.com/server-side-rendering
3. Install `@vueup/vue-quill`
4. `vite build --ssr`
5. Set up component using the `Vue Quill`-package
6. Run Laravel command to start ssr-server `php artisan inertia:start-ssr`

**Expected behavior**
I would expect SSR to work using this package.

**Comment by arffsaad** [comment]
Can send a snippet of your component that is using quill? I'm using it but have to force it under CSR because `document` is strictly a client-only element.

For now my quill looks like this:

```
<ClientOnly>
        <div class="bg-white">
            <QuillEditor theme="snow" toolbar="minimal" />
        </div>
</ClientOnly>
```
