### ISSUE TITLE
How to display the contents of the table？

### ISSUE THREAD

**Issue by ccc469** [vueup/vueup-quill#520]
**Version**
@vueup/vue-quill version [e.g. 1.2.0]

**Describe the bug**
Table contents cannot be echoed into the editor.

**To Reproduce**
1. The vue code is as follows: `<QuillEditor class="custom-editor" ref="editorRef" toolbar="#custom-editor__toolbar" v-model:content="content" :modules="modules" theme="snow" contentType="html" />

const props = defineProps({
  defaultValue: {
    type: String,
    required: false,
    default: ''
  }
});
const content = ref<string>(props.defaultValue);
console.log("🚀 ~ props:", props.defaultValue)
console.log("🚀 ~ content:", content.value)
`

Table code: `<p class="ql-table-wrapper" data-table-id="hlgmoflwflf">
    <table data-table-id="hlgmoflwflf" class="ql-table" cellpadding="0" cellspacing="0" style="width: 1275px;">
        <colgroup>
            <col width="425" data-table-id="hlgmoflwflf" data-col-id="dfxj9ufec6c">
            <col width="425" data-table-id="hlgmoflwflf" data-col-id="6qssbffugel">
            <col width="425" data-table-id="hlgmoflwflf" data-col-id="rhwai1fh33j">
        </colgroup>
        <tbody>
            <tr class="ql-table-row" data-row-id="p3lypez5ep8">
                <td class="ql-table-cell" data-row-id="p3lypez5ep8" data-col-id="dfxj9ufec6c" rowspan="1" colspan="1" style="">
                    <p class="ql-table-cell-inner" data-table-id="hlgmoflwflf" data-row-id="p3lypez5ep8" data-col-id="dfxj9ufec6c" data-rowspan="1" data-colspan="1">
                        <p>a</p>
                    </p>
                </td>
                <td class="ql-table-cell" data-row-id="p3lypez5ep8" data-col-id="6qssbffugel" rowspan="1" colspan="1" style="">
                    <p class="ql-table-cell-inner" data-table-id="hlgmoflwflf" data-row-id="p3lypez5ep8" data-col-id="6qssbffugel" data-rowspan="1" data-colspan="1">
                        <p>b</p>
                    </p>
                </td>
                <td class="ql-table-cell" data-row-id="p3lypez5ep8" data-col-id="rhwai1fh33j" rowspan="1" colspan="1" style="">
                    <p class="ql-table-cell-inner" data-table-id="hlgmoflwflf" data-row-id="p3lypez5ep8" data-col-id="rhwai1fh33j" data-rowspan="1" data-colspan="1">
                        <p>c</p>
                    </p>
                </td>
            </tr>
            <tr class="ql-table-row" data-row-id="ro7b4b9xbde">
                <td class="ql-table-cell" data-row-id="ro7b4b9xbde" data-col-id="dfxj9ufec6c" rowspan="1" colspan="1" style="">
                    <p class="ql-table-cell-inner" data-table-id="hlgmoflwflf" data-row-id="ro7b4b9xbde" data-col-id="dfxj9ufec6c" data-rowspan="1" data-colspan="1">
                        <p>1</p>
                    </p>
                </td>
                <td class="ql-table-cell" data-row-id="ro7b4b9xbde" data-col-id="6qssbffugel" rowspan="1" colspan="1" style="">
                    <p class="ql-table-cell-inner" data-table-id="hlgmoflwflf" data-row-id="ro7b4b9xbde" data-col-id="6qssbffugel" data-rowspan="1" data-colspan="1">
                        <p>2</p>
                    </p>
                </td>
                <td class="ql-table-cell" data-row-id="ro7b4b9xbde" data-col-id="rhwai1fh33j" rowspan="1" colspan="1" style="">
                    <p class="ql-table-cell-inner" data-table-id="hlgmoflwflf" data-row-id="ro7b4b9xbde" data-col-id="rhwai1fh33j" data-rowspan="1" data-colspan="1">
                        <p>3</p>
                    </p>
                </td>
            </tr>
        </tbody>
    </table>
</p>`

**Expected behavior**
Displays the table contents in the editor.

**Reproduction link**
No content.

**Browser (please complete the following information):**
 - Os  [e.g. Mac osx 14.0]
 - Browser [e.g. Chrome]
 - Version [e.g. 122.0.6261.94]

**Additional context**
Here's an example screenshot of the 'content' property having a value, but for some reason it doesn't display properly？
![image](https://github.com/vueup/vue-quill/assets/27529250/dd88fa95-bd4d-4048-807b-cefd1150c399)

**Comment by ycldz** [comment]
Hello.

I wonder how you added the table button, can you help me.
