### ISSUE TITLE
Cannot read properties of undefined (reading 'imports') when using quill-image-resize-module 

### ISSUE THREAD

**Issue by nghiaxb** [vueup/vueup-quill#521]
```
<template>
    <QuillEditor theme="snow" />
</template>
<script setup>
    import { QuillEditor } from '@vueup/vue-quill';
    import ImageResize from 'quill-image-resize-module';
</script>
```

Cannot read properties of undefined (reading 'imports') when using quill-image-resize-module

**Comment by shubhangchourasia** [comment]
I too have this issue but I have not found the solution yet.
Need solution for this

**Comment by zxr3680166** [comment]
inject({
            'window.Quill': ['vue3-quill', 'Quill'],
            Quill: ['vue3-quill', 'Quill'],
        }),
        
        这样就可以解决上述问题
