### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by iamaks1993** [vueup/vueup-quill#525]
**Version**
@vueup/vue-quill version [e.g. 1.2]

**Describe the bug**
Getting deprecation warning message when any state changes.  

dom.ts:107 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Comment by downey-lv** [comment]
Duplicate of #409
