### ISSUE TITLE
New line autoreplace and remove

### ISSUE THREAD

**Issue by Zarkheim** [vueup/vueup-quill#547]
Hello,

We recently switch to quill on our app, and a lot of content comes from our database.
However some content, like the below example : 
```
<ul>
<li style="box-sizing: inherit;">Test</li>
<li style="box-sizing: inherit;">Test</li>
<li style="box-sizing: inherit;">Test</li>
<li>&nbsp;</li>
</ul> 
```
Are automaticaly removed or replace, and we have this as a result : 
```
<p><br></p><p> </p>
```
Is there a solution to avoid this problem ?
Thanks a lot !

**Comment by cornelRaiu** [comment]
@Zarkheim maybe try to add the content type prop like so:

`<QuillEditor content-type="html" v-model:content="someHtmlContent" />`.
