### ISSUE TITLE
Vue Quill Error 

### ISSUE THREAD

**Issue by EiEiNexMind** [vueup/vueup-quill#563]
If I use vue quill editor, I am facing this error in the console "[Deprecation] Listener added for a 'DOMNodeInserted' mutation event. This event type is deprecated, and will be removed from this browser VERY soon. Usage of this event listener will cause performance issues today, and represents a large risk of imminent site breakage. Consider using MutationObserver instead. See https://chromestatus.com/feature/5083947249172480 for more information".However, even after updating to the latest version of vue-quill, this warning persists.

**Comment by cornelRaiu** [comment]
this issue was fixed in Quill v2. However, vue-quill only supports Quill up to v1.3.7.

#466 #409
