### ISSUE TITLE
i want an event that fire when the user finish typing not when he type any character

### ISSUE THREAD

**Issue by khalil-alsous** [vueup/vueup-quill#568]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.5]

**Describe the bug**
i am using quill editor in my vue app and i have some logic that sent a request when the user finish typing .. but now i am using @update:content event and its sending too many requests when the user typing

**Comment by hrynevychroman** [comment]
You can use [debounce](https://radash-docs.vercel.app/docs/curry/debounce) for this approach and set timeout to 3-5s, so when the user stops typing and passes this amount of time, the function will be executed. This is the default approach for such logic, you don't need to extend this library 🙌
