### ISSUE TITLE
Upgrade Quill dependency to the latest (version 2.0.2) from 1.3.7

### ISSUE THREAD

**Issue by Jorelia** [vueup/vueup-quill#573]
Could you please Quill as it has been updated with the version 2.0.2?

+-- @vueup/vue-quill@1.2.0
| +-- quill-delta@4.2.2
| | +-- fast-diff@1.2.0
| | +-- lodash.clonedeep@4.5.0
| | `-- lodash.isequal@4.5.0
| +-- quill@1.3.7
| | +-- clone@2.1.2
| | +-- deep-equal@1.1.1

See also: https://github.com/benwinding/quill-html-edit-button/issues/72

Thank you.

**Comment by cibilex** [comment]
I cannot use quill-mention because they use different versions.Could you please update the quill version to current one.

**Comment by imhvost** [comment]
So what's up, will there be an update or not?

**Comment by cibilex** [comment]
> So what's up, will there be an update or not?

nobady knows :)

**Comment by hannes1337** [comment]
is there a hotfix to it?

**Comment by Jorelia** [comment]
[Quill ](https://www.npmjs.com/package/quill) has published a new version. v 2.0.2 and we would like that **vueup/vue-quill** library follow the movement. We also use the library [quill-html-edit-button](https://github.com/benwinding/quill-html-edit-button) and this team has updated its library in this commit: fix [#72](https://github.com/benwinding/quill-html-edit-button/commit/f78fba1c383b48a6ebab4061235dbd97bd824815).

Running npm audit shows this message below and we hope with the new version of Quill will close the risk. 
`quill  <=1.3.7
Severity: moderate
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r`

Then, as the previous version of Quill is 1.3.7, passing to 2.0.2 is probably a breaking change for **vueup/vue-quill** and then we are waiting the update to upgrade our project and close hopefully the risk.

Thank you very much for your understanding.

**Comment by egeersoz** [comment]
Any updates? We need this ASAP.

**Comment by adrian-afl** [comment]
> Any updates? We need this ASAP.

We need to accept this library is abandoned and the only way to go forward is to fork it and then maintain the fork

**Comment by imhvost** [comment]
Will have to switch to regular Quill...

**Comment by adrian-afl** [comment]
> Will have to switch to regular Quill...

If you dig down into this library and find the code that is actually what is needed, the vue wrapper for quill, its just one file, if you remove all of those things around this library becomes very simple and you can totally just paste this 1 component into your codebase and use that, meanwhile using up to date regular quill. This has many benefits! I will go this way most likely at work because we now have a vulnerability appearing in our scans that blocks deployments.

Edit: I mean this file: https://github.com/vueup/vue-quill/blob/master/packages/vue-quill/src/components/QuillEditor.ts

**Comment by alekswebnet** [comment]
Consider using https://github.com/alekswebnet/vue-quilly.
This library only provides a Vue 3 bindings to Quill 2, you can configure Quill as you want.

**Comment by NetFlareSuperAdmin** [comment]
Need this too!

**Comment by equelly** [comment]
jljbk### bn m
